[package]
name = "middle-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trait-lib = { git = "https://github.com/liyan-ah/trait-lib.git", tag = "1.0.0" }
